/* ============================================================
   CURSO 6 UNREAL — CONTENIDO parte B (Módulos 4–7) + EXAMEN
   ============================================================ */
MODULES.push({
  id:'m4', emoji:'📦', name:'Colecciones', color:'#f97316',
  desc:'Arrays: crearlos, medirlos, recorrerlos con ForEach y hacerlos crecer.',
  lessons:[
  { id:'4-1', title:'Make Array y Array Length', time:'13 min', blocks:[
    {t:'p', h:'Un <b>array</b> es una lista ordenada de valores: el inventario del jugador, los enemigos de la oleada, los puntajes. El nodo <b>Make Array</b> crea una lista literal (editas sus elementos dentro del nodo) y <b>Array Length</b> te dice cuántos elementos tiene: un int, listo para imprimir o comparar.'},
    {t:'info', title:'ℹ️ No se puede imprimir un array entero', h:'Si conectas un array directo a un Print, el motor te lo dice claro: «no se puede imprimir un array completo: recórrelo con ForEachLoop». Los arrays no son texto: son colecciones. Por eso la pareja Make Array + ForEach (próxima lección) es inseparable.'},
    {t:'quiz', questions:[
      {type:'mc', q:'<code>Array Length</code> de un array con 7 elementos devuelve…', options:['6','7','8','Un error'], correct:1, pts:10, explain:'Length cuenta elementos: 7. (Los índices van de 0 a 6, ojo en la lección 4-3.)'},
      {type:'mc', q:'¿Qué pasa si conectas un array directo al pin Text de un Print?', options:['Imprime todos los elementos','Imprime la dirección de memoria','El motor lo rechaza: los arrays no se imprimen enteros','Convierte el array a JSON'], correct:2, pts:10, explain:'Para ver los elementos uno a uno: ForEachLoop.'},
      {type:'tf', q:'Un array puede contener 0 elementos.', options:['Verdadero','Falso'], correct:0, pts:10, explain:'El array vacío es válido y útil: Length = 0, y un ForEach sobre él no itera ni una vez.'}
    ]},
    {t:'bpex', title:'🧪 Mide tus colecciones', tasks:[
      {q:'Crea el array <code>["a","b","c"]</code> con Make Array e imprime su Length: <code>3</code>.', hint:'Make Array → pin Array del Length; Length → Text del print.', start:bG([bE(1),bP(2),bLen(3),bArr(4,['a','b','c'])],[]), check:{lines:['3']}, solution:bG([bE(1),bP(2),bLen(3),bArr(4,['a','b','c'])],[['1.then','2.in'],['4.array','3.array'],['3.length','2.text']]), pts:20},
      {q:'Inventario vacío: Make Array sin elementos → imprime su Length: <code>0</code>.', hint:'Borra todos los elementos del Make Array (déjalo vacío).', start:bG([bE(1),bP(2),bLen(3),bArr(4,[])],[]), check:{lines:['0']}, solution:bG([bE(1),bP(2),bLen(3),bArr(4,[])],[['1.then','2.in'],['4.array','3.array'],['3.length','2.text']]), pts:20},
      {q:'La despensa de la librería: array con 5 strings (<code>"café","té","cocoa","azúcar","harina"</code>) → imprime <code>5</code>.', hint:'Agrega los 5 elementos dentro del nodo Make Array.', start:bG([bE(1),bP(2),bLen(3),bArr(4,['café','té','cocoa','azúcar','harina'])],[]), check:{lines:['5']}, solution:bG([bE(1),bP(2),bLen(3),bArr(4,['café','té','cocoa','azúcar','harina'])],[['1.then','2.in'],['4.array','3.array'],['3.length','2.text']]), pts:20},
      {q:'Mensaje compuesto: imprime <code>Tienes 3 objetos</code> usando Concat: <code>"Tienes "</code> + Length, y luego <code>" objetos"</code>.', hint:'Dos Concat en cadena: el primero une "Tienes " con el Length (vía To String); su result entra al pin A del segundo Concat.', check:{lines:['Tienes 3 objetos'], requireNodes:['concat']}, solution:bG([bE(1),bP(2),bLen(3),bArr(4,['x','y','z']),bTos(5),bCat(6),bCat(7),bS(8,'Tienes '),bS(9,' objetos')],[['1.then','2.in'],['4.array','3.array'],['3.length','5.value'],['8.value','6.a'],['5.result','6.b'],['6.result','7.a'],['9.value','7.b'],['7.result','2.text']]), pts:30}
    ]}
  ]},

  { id:'4-2', title:'ForEachLoop: recorrer la colección', time:'13 min', blocks:[
    {t:'p', h:'<b>ForEachLoop</b> toma un array y ejecuta su cuerpo UNA VEZ POR ELEMENTO, en orden. En cada vuelta expone dos pines: <b>Element</b> (el valor actual) y <b>Array Index</b> (su posición: 0, 1, 2…). Al acabar todos, dispara <b>Completed</b>. Es EL nodo para inventarios, oleadas yanything que se repita con datos distintos.'},
    {t:'table', head:['Array','Vuelta','Element','Array Index'], rows:[
      ['["oro","plata"]','1.ª','"oro"','0'],
      ['["oro","plata"]','2.ª','"plata"','1'],
      ['[]','(ninguna)','—','— → dispara Completed']
    ]},
    {t:'srs', deck:'uecore', sub:'ForEach y arrays: fija el patrón que todo juego usa para inventarios y oleadas.'},
    {t:'quiz', questions:[
      {type:'mc', q:'ForEachLoop sobre un array de 4 elementos ejecuta su cuerpo…', options:['1 vez','4 veces','0 veces','Infinitas'], correct:1, pts:10, explain:'Una vuelta por elemento: 4 vueltas, con Element cambiando en cada una.'},
      {type:'mc', q:'En la primera vuelta de un ForEachLoop, Array Index vale…', options:['1','0','-1','El largo del array'], correct:1, pts:10, explain:'Los índices empiezan en 0: primera vuelta → 0.'},
      {type:'tf', q:'Si el array está vacío, ForEachLoop dispara Completed sin ejecutar el cuerpo.', options:['Verdadero','Falso'], correct:0, pts:10, explain:'Cero elementos, cero vueltas: directo a Completed.'}
    ]},
    {t:'bpex', title:'🧪 Recorre de todo', tasks:[
      {q:'ForEach sobre <code>[10,20,30]</code> imprimiendo el Element: <code>10,20,30</code>.', hint:'Element → Text del print (int entra solo).', start:bG([bE(1),bEach(2),bP(3),bArr(4,[10,20,30])],[]), check:{lines:['10','20','30']}, solution:bG([bE(1),bEach(2),bP(3),bArr(4,[10,20,30])],[['1.then','2.in'],['4.array','2.array'],['2.body','3.in'],['2.element','3.text']]), pts:25},
      {q:'Posiciones: ForEach sobre <code>["oro","plata"]</code> imprimiendo el Array Index: <code>0,1</code>.', hint:'Usa el pin Array Index, no Element.', start:bG([bE(1),bEach(2),bP(3),bArr(4,['oro','plata'])],[]), check:{lines:['0','1']}, solution:bG([bE(1),bEach(2),bP(3),bArr(4,['oro','plata'])],[['1.then','2.in'],['4.array','2.array'],['2.body','3.in'],['2.array_index','3.text']]), pts:25},
      {q:'Array vacío: ForEach sobre <code>[]</code> con <code>Completed</code> → imprime <code>Fin</code>.', hint:'El cuerpo nunca corre: solo Completed.', start:bG([bE(1),bEach(2),bP(3),bArr(4,[]),bS(5,'Fin')],[]), check:{lines:['Fin']}, solution:bG([bE(1),bEach(2),bP(3),bArr(4,[]),bS(5,'Fin')],[['1.then','2.in'],['4.array','2.array'],['2.completed','3.in'],['5.value','3.text']]), pts:20},
      {q:'Inventario etiquetado: ForEach sobre <code>["espada","poción"]</code> imprimiendo <code>Item: espada</code> y <code>Item: poción</code> (Concat "Item: " + Element).', hint:'Concat A ← "Item: ", Concat B ← Element. Tu grafo debe tener un foreach.', check:{lines:['Item: espada','Item: poción'], requireNodes:['foreach']}, solution:bG([bE(1),bEach(2),bCat(3),bP(4),bArr(5,['espada','poción']),bS(6,'Item: ')],[['1.then','2.in'],['5.array','2.array'],['2.body','4.in'],['6.value','3.a'],['2.element','3.b'],['3.result','4.text']]), pts:30}
    ]}
  ]},

  { id:'4-3', title:'Get Array Elem: leer una posición', time:'13 min', blocks:[
    {t:'p', h:'<b>Get Array Elem</b> lee UN elemento por su posición: le conectas el array y un índice int, y entrega el valor. Regla sagrada: <b>los índices empiezan en 0</b> — el primer elemento es el 0, el segundo el 1… Si pides una posición que no existe (índice 5 en un array de 3), el motor lo dice en español: «el índice 5 está fuera de rango (0..2)».'},
    {t:'info', title:'ℹ️ El truco del último elemento', h:'¿Quieres el último sin saber el largo? Combina: Length - 1. En un array de 3: 3 - 1 = 2 → el índice 2 es el tercer elemento. Verás este patrón en mil grafos profesionales.'},
    {t:'quiz', questions:[
      {type:'mc', q:'En <code>["x","y","z"]</code>, el índice del elemento "z" es…', options:['3','2','1','"z"'], correct:1, pts:10, explain:'Índices desde 0: x=0, y=1, z=2.'},
      {type:'mc', q:'Get Array Elem con índice 5 en un array de 3 elementos…', options:['Devuelve vacío','Devuelve el último','Error: fuera de rango (0..2)','Empieza de nuevo'], correct:2, pts:10, explain:'El motor avisa el rango válido: 0..2. En UE real sería un acceso inválido: aprende a verlo desde ya.'},
      {type:'tf', q:'El índice que le pases a Get Array Elem debe ser un int.', options:['Verdadero','Falso'], correct:0, pts:10, explain:'Es un entero (teal). Un float lo rechaza: si viene de una división, pásalo por To Int.'}
    ]},
    {t:'bpex', title:'🧪 Apunta bien', tasks:[
      {q:'Del podio <code>["oro","plata","bronce"]</code>, imprime el SEGUNDO lugar (índice 1): <code>plata</code>.', hint:'Literal int 1 → pin Index.', start:bG([bE(1),bP(2),bGetEl(3),bArr(4,['oro','plata','bronce']),bI(5,1)],[]), check:{lines:['plata']}, solution:bG([bE(1),bP(2),bGetEl(3),bArr(4,['oro','plata','bronce']),bI(5,1)],[['1.then','2.in'],['4.array','3.array'],['5.value','3.index'],['3.value','2.text']]), pts:25},
      {q:'El primer lugar (índice 0): <code>oro</code>.', hint:'Índice 0 = primer elemento.', start:bG([bE(1),bP(2),bGetEl(3),bArr(4,['oro','plata','bronce']),bI(5,0)],[]), check:{lines:['oro']}, solution:bG([bE(1),bP(2),bGetEl(3),bArr(4,['oro','plata','bronce']),bI(5,0)],[['1.then','2.in'],['4.array','3.array'],['5.value','3.index'],['3.value','2.text']]), pts:20},
      {q:'El bronce (índice 2): <code>bronce</code>.', hint:'Tercer elemento = índice 2.', start:bG([bE(1),bP(2),bGetEl(3),bArr(4,['oro','plata','bronce']),bI(5,2)],[]), check:{lines:['bronce']}, solution:bG([bE(1),bP(2),bGetEl(3),bArr(4,['oro','plata','bronce']),bI(5,2)],[['1.then','2.in'],['4.array','3.array'],['5.value','3.index'],['3.value','2.text']]), pts:20},
      {q:'El último siempre: del array <code>["a","b","c"]</code>, usa <code>Length - 1</code> (Aritmética −) como índice → <code>c</code>.', hint:'Length(3) → pin A del nodo −; literal 1 al pin B; result al Index.', check:{lines:['c'], requireNodes:['array_get']}, solution:bG([bE(1),bP(2),bGetEl(3),bArr(4,['a','b','c']),bLen(5),bAr(6,'-'),bI(7,1)],[['1.then','2.in'],['4.array','3.array'],['4.array','5.array'],['5.length','6.a'],['7.value','6.b'],['6.result','3.index'],['3.value','2.text']]), pts:30}
    ]}
  ]},

  { id:'4-4', title:'Array Add: inventarios que crecen', time:'13 min', blocks:[
    {t:'p', h:'<b>Array Add</b> recibe un array y un elemento, y devuelve <b>un array nuevo con el elemento al final</b> (no modifica el original: por eso su salida vuelve a conectarse a un Set para guardar el cambio). El patrón completo de inventario: <code>Set inventario = Array Add(Get inventario, nuevo item)</code>.'},
    {t:'warn', title:'⚠️ Add no toca tu variable', h:'Error clásico: conectar Add y esperar que «la variable crezca sola». Array Add entrega un array NUEVO; si no lo guardas con Set, se pierde. En UE real el nodo de arrays sí modifica (es referencia); aquí separamos el paso para que entiendas QUÉ pasa exactamente.'},
    {t:'quiz', questions:[
      {type:'mc', q:'Array Add entrega…', options:['El mismo array modificado','Un array nuevo con el elemento agregado al final','El elemento agregado','El Length nuevo'], correct:1, pts:10, explain:'Por eso se combina con Set: para persistir el array crecido.'},
      {type:'mc', q:'El elemento agregado con Array Add queda…', options:['Al inicio','En medio','Al final','En posición aleatoria'], correct:2, pts:10, explain:'Add siempre empuja al final: posición Length del array nuevo.'},
      {type:'tf', q:'Para que el inventario crezca de verdad, la salida de Array Add debe guardarse con Set.', options:['Verdadero','Falso'], correct:0, pts:10, explain:'Sin Set, el array crecido se pierde al terminar la cadena.'}
    ]},
    {t:'bpex', title:'🧪 Crece tu inventario', tasks:[
      {q:'Agrega <code>"poción"</code> al array <code>["espada"]</code> e imprime el Length resultante: <code>2</code>.', hint:'Array Add → Length. No hace falta variable todavía.', start:bG([bE(1),bP(2),bLen(3),bAdd(4),bArr(5,['espada']),bS(6,'poción')],[]), check:{lines:['2']}, solution:bG([bE(1),bP(2),bLen(3),bAdd(4),bArr(5,['espada']),bS(6,'poción')],[['1.then','2.in'],['5.array','4.array'],['6.value','4.item'],['4.result','3.array'],['3.length','2.text']]), pts:25},
      {q:'El patrón completo: <code>inv</code> empieza como <code>["espada"]</code> (Set), Add <code>"poción"</code> → Set otra vez, y ForEach imprime: <code>espada</code>, <code>poción</code>.', hint:'Exec: Set inv → Set inv (con Add(Get inv, poción)) → ForEach(Get inv).', check:{lines:['espada','poción'], vars:{inv:['espada','poción']}}, solution:bG([bE(1),bSet(2,'inv','array'),bSet(3,'inv','array'),bAdd(4),bGet(5,'inv','array'),bGet(6,'inv','array'),bEach(7),bP(8),bArr(9,['espada']),bS(10,'poción')],[['1.then','2.in'],['9.array','2.value'],['2.then','3.in'],['5.value','4.array'],['10.value','4.item'],['4.result','3.value'],['3.then','7.in'],['6.value','7.array'],['7.body','8.in'],['7.element','8.text']]), pts:35},
      {q:'Botín triple: partiendo de <code>["plata"]</code>, agrega <code>"bronce"</code> y luego <code>"oro"</code>; ForEach imprime los tres: <code>plata,bronce,oro</code>.', hint:'Dos Sets encadenados, cada uno con su Add.', check:{lines:['plata','bronce','oro']}, solution:bG([bE(1),bSet(2,'inv','array'),bSet(3,'inv','array'),bSet(4,'inv','array'),bAdd(5),bAdd(6),bGet(7,'inv','array'),bGet(8,'inv','array'),bGet(9,'inv','array'),bEach(10),bP(11),bArr(12,['plata']),bS(13,'bronce'),bS(14,'oro')],[['1.then','2.in'],['12.array','2.value'],['2.then','3.in'],['7.value','5.array'],['13.value','5.item'],['5.result','3.value'],['3.then','4.in'],['8.value','6.array'],['14.value','6.item'],['6.result','4.value'],['4.then','10.in'],['9.value','10.array'],['10.body','11.in'],['10.element','11.text']]), pts:35},
      {q:'Bolsa de botín: <code>botin</code> empieza vacío; agrega <code>"moneda"</code>, <code>"gema"</code>, <code>"llave"</code>; imprime el Length final: <code>3</code>.', hint:'Set botin = [] y luego tres Set con Add.', check:{lines:['3'], vars:{botin:['moneda','gema','llave']}}, solution:bG([bE(1),bSet(2,'botin','array'),bSet(3,'botin','array'),bSet(4,'botin','array'),bSet(5,'botin','array'),bAdd(6),bAdd(7),bAdd(8),bGet(9,'botin','array'),bGet(10,'botin','array'),bGet(11,'botin','array'),bGet(12,'botin','array'),bLen(13),bP(14),bArr(15,[]),bS(16,'moneda'),bS(17,'gema'),bS(18,'llave')],[['1.then','2.in'],['15.array','2.value'],['2.then','3.in'],['9.value','6.array'],['16.value','6.item'],['6.result','3.value'],['3.then','4.in'],['10.value','7.array'],['17.value','7.item'],['7.result','4.value'],['4.then','5.in'],['11.value','8.array'],['18.value','8.item'],['8.result','5.value'],['5.then','14.in'],['12.value','13.array'],['13.length','14.text']]), pts:40}
    ]}
  ]}
]});

MODULES.push({
  id:'m5', emoji:'🛡️', name:'Comunicación y robustez', color:'#14b8a6',
  desc:'Custom Events, llamadas entre grafos y cómo leer los errores del motor.',
  lessons:[
  { id:'5-1', title:'Custom Events: tus propios nodos', time:'13 min', blocks:[
    {t:'p', h:'Un <b>Custom Event</b> es un trozo de lógica con nombre que TÚ creas: como una función. Se define una vez (nodo rojo con nombre propio) y se ejecuta donde quieras con el nodo <b>Call</b>. Cuando el Call salta al evento, este corre COMPLETO y la ejecución <b>regresa</b> justo después del Call. Es la herramienta para organizar grafos grandes: «TurnoJugador», «AbrirTienda», «SpawnOleada».'},
    {t:'info', title:'ℹ️ Divide y vencerás', h:'Un BeginPlay de 80 nodos es imposible de mantener. Los profesionales lo parten en Custom Events con nombres claros: el BeginPlay solo llama eventos en orden. Regla de oro: si necesitas un comentario para explicar un bloque, ese bloque merece ser un evento.'},
    {t:'srs', deck:'uecore', sub:'Custom Events y llamadas: la organización que separa a los pros de los principiantes.'},
    {t:'quiz', questions:[
      {type:'mc', q:'Un Custom Event es…', options:['Un tipo de variable','Un bloque de lógica con nombre que puedes invocar','Un nodo que solo imprime','Un error del motor'], correct:1, pts:10, explain:'Es tu propio nodo: define una vez, llama donde quieras.'},
      {type:'mc', q:'Cuando un Call termina de ejecutar el evento…', options:['El juego se reinicia','La ejecución REGRESA al nodo siguiente del Call','El evento se borra','Salta a otro evento al azar'], correct:1, pts:10, explain:'Es como una función: ejecuta, regresa y continúa la cadena del Call.'},
      {type:'tf', q:'Puedes llamar al mismo Custom Event desde varios lugares del grafo.', options:['Verdadero','Falso'], correct:0, pts:10, explain:'Ese es justamente el ahorro: lógica escrita una vez, usada N veces.'}
    ]},
    {t:'bpex', title:'🧪 Tu primer evento', tasks:[
      {q:'Crea el Custom Event <code>Saludo</code> que imprime <code>Hola del evento</code>. Desde BeginPlay: Call <code>Saludo</code> → imprime <code>Fin</code>. Salida: las dos líneas en ese orden.', hint:'El pin Then del Call continúa DESPUÉS de que el evento termina.', check:{lines:['Hola del evento','Fin'], requireNodes:['event_custom','call_custom']}, solution:bG([bE(1),bCall(2,'Saludo'),bP(3),bCev(4,'Saludo'),bP(5),bS(6,'Hola del evento'),bS(7,'Fin')],[['1.then','2.in'],['2.then','3.in'],['4.then','5.in'],['6.value','5.text'],['7.value','3.text']]), pts:30},
      {q:'Rodea la llamada: imprime <code>Inicio</code>, luego Call <code>Rutina</code> (imprime <code>Dentro</code>), luego imprime <code>Fin</code>.', hint:'BeginPlay → Print Inicio → Call → Print Fin. El evento es aparte.', check:{lines:['Inicio','Dentro','Fin']}, solution:bG([bE(1),bP(2),bCall(3,'Rutina'),bP(4),bCev(5,'Rutina'),bP(6),bS(7,'Inicio'),bS(8,'Dentro'),bS(9,'Fin')],[['1.then','2.in'],['2.then','3.in'],['3.then','4.in'],['5.then','6.in'],['7.value','2.text'],['8.value','6.text'],['9.value','4.text']]), pts:30},
      {q:'Doble llamada: BeginPlay → Call <code>Ping</code> → Call <code>Ping</code> → imprime <code>Listo</code>. El evento imprime <code>Ping</code>. Salida: <code>Ping,Ping,Listo</code>.', hint:'Dos Calls en cadena: cada uno ejecuta el evento completo antes de seguir.', check:{lines:['Ping','Ping','Listo']}, solution:bG([bE(1),bCall(2,'Ping'),bCall(3,'Ping'),bP(4),bCev(5,'Ping'),bP(6),bS(7,'Listo'),bS(8,'Ping')],[['1.then','2.in'],['2.then','3.in'],['3.then','4.in'],['5.then','6.in'],['8.value','6.text'],['7.value','4.text']]), pts:30},
      {q:'Menú organizado: el evento <code>MostrarMenu</code> imprime <code>MENÚ</code>, <code>1. Jugar</code>, <code>2. Salir</code>; el BeginPlay lo llama y luego imprime <code>Elige: </code>.', hint:'El menú completo vive DENTRO del evento: por eso se reutiliza.', check:{lines:['MENÚ','1. Jugar','2. Salir','Elige: '], requireNodes:['event_custom','call_custom']}, solution:bG([bE(1),bCall(2,'MostrarMenu'),bP(3),bCev(4,'MostrarMenu'),bP(5),bP(6),bP(7),bS(8,'MENÚ'),bS(9,'1. Jugar'),bS(10,'2. Salir'),bS(11,'Elige: ')],[['1.then','2.in'],['2.then','3.in'],['4.then','5.in'],['5.then','6.in'],['6.then','7.in'],['8.value','5.text'],['9.value','6.text'],['10.value','7.text'],['11.value','3.text']]), pts:35}
    ]}
  ]},

  { id:'5-2', title:'Llamadas anidadas y el patrón menú → acción', time:'13 min', blocks:[
    {t:'p', h:'Los Custom Events pueden <b>llamar a otros Custom Events</b>, formando una cadena de responsabilidades. La regla de orden es la de toda función: la llamada más profunda TERMINA PRIMERO. Si BeginPlay llama a «Uno» y «Uno» llama a «Dos», el orden de impresión es: lo de «Dos», lo de «Uno», y al final lo que seguía en BeginPlay.'},
    {t:'info', title:'ℹ️ El patrón menú → acción', h:'Los juegos de menú funcionan así: un evento <code>MostrarMenu</code> imprime las opciones; cuando el jugador elige, otro bloque llama al evento de la acción (<code>Jugar</code>, <code>Tienda</code>). Cada pieza es pequeña, tiene nombre claro y se puede arreglar sin romper las demás. Este patrón lo escribirás en el proyecto final.'},
    {t:'quiz', questions:[
      {type:'mc', q:'BeginPlay llama a <code>Uno</code>; <code>Uno</code> llama a <code>Dos</code>. ¿Qué termina de imprimirse PRIMERO?', options:['BeginPlay','Uno','Dos','Los tres a la vez'], correct:2, pts:10, explain:'La llamada más profunda termina primero: Dos, luego Uno, luego lo que seguía en BeginPlay.'},
      {type:'mc', q:'Si un Custom Event no existe cuando lo llamas…', options:['Se crea solo','El motor avisa: no existe ningún evento con ese nombre','Corre un evento vacío','Se reinicia el juego'], correct:1, pts:10, explain:'Revisa el nombre EXACTO (mayúsculas incluidas): el error te lo dice.'},
      {type:'tf', q:'Un evento puede imprimir varias líneas y luego devolver el control al Call.', options:['Verdadero','Falso'], correct:0, pts:10, explain:'El evento es un grafo completo: lo que se te ocurra adentro, y al acabar regresas.'}
    ]},
    {t:'bpex', title:'🧪 Cadenas de responsabilidad', tasks:[
      {q:'Anidadas: BeginPlay → Call <code>Uno</code> → imprime <code>inicio</code>. <code>Uno</code> → Call <code>Dos</code> → imprime <code>uno</code>. <code>Dos</code> imprime <code>dos</code>. Salida esperada: <code>dos,uno,inicio</code>.', hint:'La más profunda primero. Sigue el regreso: Dos termina → sigue Uno → sigue BeginPlay.', check:{lines:['dos','uno','inicio']}, solution:bG([bE(1),bCall(2,'Uno'),bP(3),bCev(4,'Uno'),bCall(5,'Dos'),bP(6),bCev(7,'Dos'),bP(8),bS(9,'inicio'),bS(10,'uno'),bS(11,'dos')],[['1.then','2.in'],['2.then','3.in'],['4.then','5.in'],['5.then','6.in'],['7.then','8.in'],['9.value','3.text'],['10.value','6.text'],['11.value','8.text']]), pts:35},
      {q:'Calentamiento: Call <code>Rutina</code> que usa un Sequence: Then 0 imprime <code>Estirar</code>, Then 1 imprime <code>En posición</code>. Después del Call, imprime <code>Whistle</code>.', hint:'Los eventos pueden usar CUALQUIER nodo por dentro: sequence, branch, ciclos…', check:{lines:['Estirar','En posición','Whistle']}, solution:bG([bE(1),bCall(2,'Rutina'),bP(3),bCev(4,'Rutina'),bSeq(5),bP(6),bP(7),bS(8,'Estirar'),bS(9,'En posición'),bS(10,'Whistle')],[['1.then','2.in'],['2.then','3.in'],['4.then','5.in'],['5.then0','6.in'],['5.then1','7.in'],['8.value','6.text'],['9.value','7.text'],['10.value','3.text']]), pts:35},
      {q:'Menú funcional: evento <code>MostrarMenu</code> imprime <code>MENÚ</code> y <code>1. Jugar</code>; BeginPlay lo llama y después imprime <code>Elige: </code>.', hint:'Igual que 5-1 t4 pero ahora con dos líneas dentro del evento.', check:{lines:['MENÚ','1. Jugar','Elige: ']}, solution:bG([bE(1),bCall(2,'MostrarMenu'),bP(3),bCev(4,'MostrarMenu'),bP(5),bP(6),bS(7,'MENÚ'),bS(8,'1. Jugar'),bS(9,'Elige: ')],[['1.then','2.in'],['2.then','3.in'],['4.then','5.in'],['5.then','6.in'],['7.value','5.text'],['8.value','6.text'],['9.value','3.text']]), pts:30},
      {q:'Orden con eventos: BeginPlay imprime <code>A</code>, llama a <code>Ruido</code> (imprime <code>E1</code> y <code>E2</code>), y luego imprime <code>B</code>.', hint:'A → (dentro: E1, E2) → B. El Call es transparente para el orden externo.', check:{lines:['A','E1','E2','B']}, solution:bG([bE(1),bP(2),bCall(3,'Ruido'),bP(4),bCev(5,'Ruido'),bP(6),bP(7),bS(8,'A'),bS(9,'E1'),bS(10,'E2'),bS(11,'B')],[['1.then','2.in'],['2.then','3.in'],['3.then','4.in'],['5.then','6.in'],['6.then','7.in'],['8.value','2.text'],['9.value','6.text'],['10.value','7.text'],['11.value','4.text']]), pts:30}
    ]}
  ]},

  { id:'5-3', title:'Leer y arreglar: los errores del motor', time:'13 min', blocks:[
    {t:'p', h:'Los errores de Blueprints son <b>amigos que gritan de noche</b>: incomodos, pero te salvan. El motor de este curso siempre dice <b>qué nodo</b> falló y <b>qué pin</b> falta, en español: «Nodo #4 (Set Variable): la entrada esperaba un entero… usa To Int (Truncate)». Hoy entrenarás el reflejo profesional: leer el error, entenderlo, arreglar el grafo.'},
    {t:'table', head:['Mensaje','Causa','Arreglo'], rows:[
      ['la entrada «Condición» no está conectada','Branch sin bool','Conecta un Comparar o literal bool'],
      ['esperaba un entero… usa To Int (Truncate)','float donde va int','Inserta To Int en el cable'],
      ['la variable aún no tiene valor','Get antes que Set','Mueve/conecta un Set antes en la ejecución'],
      ['no termina nunca','WhileLoop sin salida','Haz que el cuerpo cambie la condición'],
      ['no existe ningún Custom Event llamado…','Call con nombre equivocado','Corrige el nombre exacto']
    ]},
    {t:'quiz', questions:[
      {type:'mc', q:'El error «Nodo #3 (Branch): la entrada Condición no está conectada» significa…', options:['El Branch está roto para siempre','Falta conectar un bool al pin Condition','Falta un print','El BeginPlay no existe'], correct:1, pts:10, explain:'El nodo y el pin exactos están en el mensaje: conecta un bool ahí.'},
      {type:'mc', q:'Si un Set de variable int recibe un float, el arreglo es…', options:['Cambiar el float a string','Insertar un To Int (Truncate) entre ambos','Ignorarlo, funciona igual','Reiniciar el editor'], correct:1, pts:10, explain:'El mensaje lo dice: UE exige conversión EXPLÍCITA hacia int.'},
      {type:'tf', q:'«El WhileLoop no termina nunca» se arregla asegurando que el cuerpo cambie algo que la condición revisa.', options:['Verdadero','Falso'], correct:0, pts:10, explain:'Contadores que suben, vidas que bajan, banderas que se voltean: la salida del laberinto.'}
    ]},
    {t:'bpex', title:'🧪 Modo de reparación (grafos rotos incluidos)', tasks:[
      {q:'REPARA: el Branch no tiene condición. Conecta el literal bool <code>true</code> al pin Condition y ejecuta: <code>Ruta segura</code>.', hint:'Clic en el pin Condition (o en el cable roto) y luego en la salida del literal.', start:bG([bE(1),bBr(2),bP(3),bB(4,true),bS(5,'Ruta segura')],[['1.then','2.in'],['2.true','3.in'],['5.value','3.text']]), check:{lines:['Ruta segura']}, solution:bG([bE(1),bBr(2),bP(3),bB(4,true),bS(5,'Ruta segura')],[['1.then','2.in'],['2.true','3.in'],['4.value','2.cond'],['5.value','3.text']]), pts:25},
      {q:'REPARA: el float <code>2.7</code> entra directo a un Set de int (error). Inserta un <b>To Int</b> en el cable. Al ejecutar: <code>2</code> y monedas queda en 2.', hint:'Desconecta el cable float→Set, agrega To Int: float → To Int → Set.', start:bG([bE(1),bSet(2,'monedas'),bGet(3,'monedas'),bP(4),bF(5,2.7)],[['1.then','2.in'],['2.then','4.in'],['5.value','2.value'],['3.value','4.text']]), check:{lines:['2'], vars:{monedas:2}}, solution:bG([bE(1),bSet(2,'monedas'),bGet(3,'monedas'),bP(4),bF(5,2.7),bToi(6)],[['1.then','2.in'],['2.then','4.in'],['5.value','6.value'],['6.result','2.value'],['3.value','4.text']]), pts:30},
      {q:'REPARA: el Branch muestra <code>Derrota</code> pero la vida es 100. Quita el literal false del Condition y conecta el Comparar <code>(vida > 0)</code> que ya está en el grafo. Resultado: <code>Victoria</code>.', hint:'El cable equivocado va del literal false al Condition; reemplázalo con el result del Comparar.', start:bG([bE(1),bSet(2,'vida'),bBr(3),bP(4),bP(5),bGet(6,'vida'),bCmp(7,'>'),bI(8,100),bI(9,0),bB(10,false),bS(11,'Victoria'),bS(12,'Derrota')],[['1.then','2.in'],['8.value','2.value'],['2.then','3.in'],['3.true','4.in'],['3.false','5.in'],['9.value','7.b'],['6.value','7.a'],['10.value','3.cond'],['11.value','4.text'],['12.value','5.text']]), check:{lines:['Victoria'], requireNodes:['branch']}, solution:bG([bE(1),bSet(2,'vida'),bBr(3),bP(4),bP(5),bGet(6,'vida'),bCmp(7,'>'),bI(8,100),bI(9,0),bB(10,false),bS(11,'Victoria'),bS(12,'Derrota')],[['1.then','2.in'],['8.value','2.value'],['2.then','3.in'],['3.true','4.in'],['3.false','5.in'],['9.value','7.b'],['6.value','7.a'],['7.result','3.cond'],['11.value','4.text'],['12.value','5.text']]), pts:30}
    ]}
  ]}
]});

MODULES.push({
  id:'m6', emoji:'🕹️', name:'Patrones de juego', color:'#ef4444',
  desc:'Vida y daño, oleadas, estados de partida… y el salto al editor real de UE 5.8.',
  lessons:[
  { id:'6-1', title:'Vida y daño: el contador sagrado', time:'13 min', blocks:[
    {t:'p', h:'Toda la industria gira alrededor de un patrón: <b>un número que baja</b>. La vida, el escudo, el tiempo, la paciencia del boss final. El patrón completo: inicializas con Set, restas daño con Aritmética, y con un Branch decides si llegó a cero. Domina esto y ya entiendes el 50% de todo juego de acción.'},
    {t:'info', title:'ℹ️ Golpes en cadena', h:'Tres golpes de 30 a una vida de 100: Set vida=100 → print → Set vida = vida−30 → print → … Cada print intermedio es tu ventana de depuración: ves 100, 70, 40, 10 y confirmas que la cuenta cuadra. Sin prints, estarías adivinando.'},
    {t:'quiz', questions:[
      {type:'mc', q:'Vida = 50, llega un golpe de 20. ¿Qué patrón actualiza la vida?', options:['Set vida = 20','Set vida = vida − 20 (Aritmética con Get)','Print vida','Branch vida'], correct:1, pts:10, explain:'El patrón Set(Get op literal): lee el valor actual, aplica el daño, guarda.'},
      {type:'mc', q:'Para detectar derrota cuando la vida llega a cero o menos, la condición es…', options:['vida > 0','vida <= 0','vida == 100','NOT vida'], correct:1, pts:10, explain:'<= 0 cubre el cero Y los negativos (daño de sobregolpe).'},
      {type:'tf', q:'Un escudo que absorbe daño se calcula restando el escudo al golpe ANTES de tocar la vida.', options:['Verdadero','Falso'], correct:0, pts:10, explain:'Daño real = golpe − escudo. Si el escudo cubre todo, la vida ni se entera.'}
    ]},
    {t:'bpex', title:'🧪 El corazón del combate', tasks:[
      {q:'Vida inicial <code>100</code>: imprime la vida, aplica 3 golpes de <code>30</code> (imprimiendo después de cada uno). Salida: <code>100,70,40,10</code>.', hint:'Cadena: Set 100 → Print → Set(vida−30) → Print → Set → Print → Set → Print.', check:{lines:['100','70','40','10'], vars:{vida:10}}, solution:bG([bE(1),bSet(2,'vida'),bP(3),bSet(4,'vida'),bP(5),bSet(6,'vida'),bP(7),bSet(8,'vida'),bP(9),bGet(10,'vida'),bAr(11,'-'),bI(12,100),bI(13,30),bAr(14,'-'),bAr(15,'-')],[['1.then','2.in'],['12.value','2.value'],['2.then','3.in'],['3.then','4.in'],['10.value','11.a'],['13.value','11.b'],['11.result','4.value'],['4.then','5.in'],['5.then','6.in'],['10.value','14.a'],['13.value','14.b'],['14.result','6.value'],['6.then','7.in'],['7.then','8.in'],['10.value','15.a'],['13.value','15.b'],['15.result','8.value'],['8.then','9.in'],['10.value','3.text'],['10.value','5.text'],['10.value','7.text'],['10.value','9.text']]), pts:35},
      {q:'Derrota: <code>vida</code> = 0; Branch con <code>vida <= 0</code> → imprime <code>Game Over</code>.', hint:'Comparar <=: 0 contra 0 da true.', check:{lines:['Game Over'], requireNodes:['branch']}, solution:bG([bE(1),bSet(2,'vida'),bBr(3),bP(4),bGet(5,'vida'),bCmp(6,'<='),bI(7,0),bS(8,'Game Over')],[['1.then','2.in'],['7.value','2.value'],['2.then','3.in'],['5.value','6.a'],['7.value','6.b'],['6.result','3.cond'],['3.true','4.in'],['8.value','4.text']]), pts:25},
      {q:'Poción de vida: <code>vida</code> = 20, bebes una poción de <code>+45</code>, imprime la vida: <code>65</code>.', hint:'El mismo patrón con suma.', check:{lines:['65'], vars:{vida:65}}, solution:bG([bE(1),bSet(2,'vida'),bSet(3,'vida'),bGet(4,'vida'),bP(5),bAr(6,'+'),bI(7,20),bI(8,45)],[['1.then','2.in'],['7.value','2.value'],['2.then','3.in'],['4.value','6.a'],['8.value','6.b'],['6.result','3.value'],['3.then','5.in'],['4.value','5.text']]), pts:25},
      {q:'Escudo: el golpe es de <code>60</code>, el escudo absorbe <code>50</code>. Calcula e imprime <code>Daño real: 10</code> (Concat "Daño real: " + (60 − 50)).', hint:'Aritmética − con 60 y 50; el result por To String al Concat.', check:{lines:['Daño real: 10'], requireNodes:['concat']}, solution:bG([bE(1),bP(2),bAr(3,'-'),bI(4,60),bI(5,50),bTos(6),bCat(7),bS(8,'Daño real: ')],[['1.then','2.in'],['4.value','3.a'],['5.value','3.b'],['3.result','6.value'],['8.value','7.a'],['6.result','7.b'],['7.result','2.text']]), pts:30}
    ]}
  ]},

  { id:'6-2', title:'Oleadas y monedas: ciclos que acumulan', time:'13 min', blocks:[
    {t:'p', h:'Aquí se juntan TODO lo aprendido en el patrón más jugoso del curso: <b>el acumulador</b>. Una variable empieza en 0; un ciclo (ForLoop para vueltas fijas, ForEach para colecciones) le suma algo en cada vuelta; al final, la variable guarda el total. Oro por oleada, botín por enemigo, puntos por ronda: siempre el mismo esqueleto.'},
    {t:'code', lang:'pseudocódigo', title:'el esqueleto del acumulador', code:`total = 0                      ← Set total = 0
PARA CADA botín EN [5, 10, 20]   ← ForEach
    total = total + botín        ← Set total = Get total + Element
IMPRIMIR total                   ← 35 (conectado a Completed)`},
    {t:'quiz', questions:[
      {type:'mc', q:'¿Qué suma <code>total = total + 10</code> tres veces si total empieza en 0?', options:['10','20','30','0'], correct:2, pts:10, explain:'0→10→20→30: el acumulador recuerda la suma de todas las vueltas.'},
      {type:'mc', q:'En el patrón botín, el Set del acumulador va…', options:['Antes del ciclo','DENTRO del cuerpo del ciclo','En el Completed','En otro evento'], correct:1, pts:10, explain:'Cada vuelta aporta su suma: el Set vive en el cuerpo; el print, en Completed.'},
      {type:'tf', q:'Para vueltas de cantidad fija (siempre 3 oleadas), ForLoop es la elección natural.', options:['Verdadero','Falso'], correct:0, pts:10, explain:'Sabes N → ForLoop. Para recorrer colecciones de tamaño variable → ForEach.'}
    ]},
    {t:'bpex', title:'🧪 La economía del juego', tasks:[
      {q:'Tres oleadas con letrero: ForLoop 1..3 que imprime <code>Oleada 1</code>, <code>Oleada 2</code>, <code>Oleada 3</code> (Concat). Tu grafo debe tener un forloop.', hint:'Concat "Oleada " + To String(Index).', check:{lines:['Oleada 1','Oleada 2','Oleada 3'], requireNodes:['forloop']}, solution:bG([bE(1),bFor(2),bCat(3),bP(4),bTos(5),bS(6,'Oleada '),bI(7,1),bI(8,3)],[['1.then','2.in'],['7.value','2.first'],['8.value','2.last'],['2.body','4.in'],['6.value','3.a'],['2.index','5.value'],['5.result','3.b'],['3.result','4.text']]), pts:25},
      {q:'Oro por oleada: <code>oro</code> = 0; ForLoop 1..3 cuyo cuerpo suma <code>+10</code> al oro e imprime el oro actual. Salida: <code>10,20,30</code> y oro termina en 30.', hint:'Cuerpo: Set oro = Get oro + 10; print con Get. Dos nodos en el cuerpo, en cadena.', check:{lines:['10','20','30'], vars:{oro:30}}, solution:bG([bE(1),bSet(2,'oro'),bFor(3),bSet(4,'oro'),bP(5),bGet(6,'oro'),bAr(7,'+'),bI(8,0),bI(9,10),bI(10,1),bI(11,3)],[['1.then','2.in'],['8.value','2.value'],['2.then','3.in'],['10.value','3.first'],['11.value','3.last'],['3.body','4.in'],['6.value','7.a'],['9.value','7.b'],['7.result','4.value'],['3.body','5.in'],['6.value','5.text']]), pts:35},
      {q:'Botín total: <code>total</code> = 0; ForEach sobre <code>[5,10,20]</code> suma cada Element al total; en Completed imprime el total: <code>35</code>.', hint:'El print va en Completed (fuera del cuerpo), leyendo la variable.', check:{lines:['35'], requireNodes:['foreach']}, solution:bG([bE(1),bSet(2,'total'),bEach(3),bSet(4,'total'),bGet(5,'total'),bP(6),bArr(7,[5,10,20]),bAr(8,'+'),bI(9,0)],[['1.then','2.in'],['9.value','2.value'],['2.then','3.in'],['7.array','3.array'],['3.body','4.in'],['5.value','8.a'],['3.element','8.b'],['8.result','4.value'],['3.completed','6.in'],['5.value','6.text']]), pts:35},
      {q:'Botín con premio: como la tarea anterior, pero tras el ciclo un Branch decide: si <code>total >= 20</code> imprime <code>¡Botín rico!</code> (y si no, <code>Botín pobre</code>). Con [5,10,20] sale lo primero.', hint:'Completed → Branch; la condición compara la variable acumulada.', check:{lines:['¡Botín rico!'], requireNodes:['branch']}, solution:bG([bE(1),bSet(2,'total'),bEach(3),bSet(4,'total'),bGet(5,'total'),bBr(6),bP(7),bP(8),bCmp(9,'>='),bI(10,20),bArr(11,[5,10,20]),bAr(12,'+'),bI(13,0),bS(14,'¡Botín rico!'),bS(15,'Botín pobre')],[['1.then','2.in'],['13.value','2.value'],['2.then','3.in'],['11.array','3.array'],['3.body','4.in'],['5.value','12.a'],['3.element','12.b'],['12.result','4.value'],['3.completed','6.in'],['5.value','9.a'],['10.value','9.b'],['9.result','6.cond'],['6.true','7.in'],['6.false','8.in'],['14.value','7.text'],['15.value','8.text']]), pts:40}
    ]}
  ]},

  { id:'6-3', title:'Estados de partida: victoria, derrota y turnos', time:'13 min', blocks:[
    {t:'p', h:'Un juego es una máquina de estados: <b>jugando → ganó / perdió</b>, turnos que rotan, menús que abren y cierran. En Blueprints estos estados se modelan con las piezas que ya dominas: Branches encadenados para decidir el estado, FlipFlop para alternar turnos y Custom Events para que cada estado sea un bloque con nombre.'},
    {t:'info', title:'ℹ️ La pantalla final', h:'El «Game Over» o la «Victoria» son como cualquier otro print: lo que cambia es QUIÉN decide mostrarlos. Un Branch al final de la lógica (¿vida <= 0? ¿monedas >= meta?) elige entre dos eventos: <code>PantallaVictoria</code> o <code>PantallaDerrota</code>. En el proyecto final lo construirás completo.'},
    {t:'quiz', questions:[
      {type:'mc', q:'Para alternar «turno del héroe» y «turno del monstruo» el nodo ideal es…', options:['Branch','Sequence','FlipFlop','ForLoop'], correct:2, pts:10, explain:'FlipFlop alterna A/B en cada ejecución: turnos por diseño.'},
      {type:'mc', q:'La condición de victoria «recolecta 50 monedas» se evalúa con…', options:['Un print','Branch con Comparar oro >= 50','Un array','To Int'], correct:1, pts:10, explain:'Comparar fabrica el bool; el Branch ejecuta la pantalla que toca.'},
      {type:'tf', q:'Cada estado de la partida conviene vivir en su propio Custom Event con nombre descriptivo.', options:['Verdadero','Falso'], correct:0, pts:10, explain:'PantallaVictoria, PantallaDerrota, TurnoJugador…: grafos legibles y arreglables.'}
    ]},
    {t:'bpex', title:'🧪 La partida decide', tasks:[
      {q:'Meta cumplida: <code>oro</code> = 60; Branch con <code>oro >= 50</code>: True imprime <code>¡Victoria!</code>, False <code>Casi...</code>.', hint:'El Comparar fabrica el bool del Branch.', check:{lines:['¡Victoria!']}, solution:bG([bE(1),bSet(2,'oro'),bBr(3),bP(4),bP(5),bGet(6,'oro'),bCmp(7,'>='),bI(8,60),bI(9,50),bS(10,'¡Victoria!'),bS(11,'Casi...')],[['1.then','2.in'],['8.value','2.value'],['2.then','3.in'],['6.value','7.a'],['9.value','7.b'],['7.result','3.cond'],['3.true','4.in'],['3.false','5.in'],['10.value','4.text'],['11.value','5.text']]), pts:25},
      {q:'Turnos: ForLoop 1..2 → FlipFlop: A imprime <code>Turno del héroe</code>, B imprime <code>Turno del slime</code>.', hint:'Dos vueltas, dos turnos alternados.', check:{lines:['Turno del héroe','Turno del slime']}, solution:bG([bE(1),bFor(2),bFF(3),bP(4),bP(5),bS(6,'Turno del héroe'),bS(7,'Turno del slime'),bI(8,1),bI(9,2)],[['1.then','2.in'],['8.value','2.first'],['9.value','2.last'],['2.body','3.in'],['3.a','4.in'],['3.b','5.in'],['6.value','4.text'],['7.value','5.text']]), pts:25},
      {q:'Caída de la librería: <code>vida</code> = 0; Branch <code>vida <= 0</code> → True imprime <code>La librería cayó...</code>.', hint:'Condición <= 0 con el Get de vida.', check:{lines:['La librería cayó...']}, solution:bG([bE(1),bSet(2,'vida'),bBr(3),bP(4),bGet(5,'vida'),bCmp(6,'<='),bI(7,0),bS(8,'La librería cayó...')],[['1.then','2.in'],['7.value','2.value'],['2.then','3.in'],['5.value','6.a'],['7.value','6.b'],['6.result','3.cond'],['3.true','4.in'],['8.value','4.text']]), pts:25},
      {q:'Pantalla final con evento: el evento <code>PantallaFinal</code> imprime <code>GAME OVER</code> y <code>Reintentar?</code>; BeginPlay lo llama y luego imprime <code>Créditos</code>. Debe tener call_custom.', hint:'La pantalla final es un evento: reutilizable desde cualquier derrota.', check:{lines:['GAME OVER','Reintentar?','Créditos'], requireNodes:['call_custom']}, solution:bG([bE(1),bCall(2,'PantallaFinal'),bP(3),bCev(4,'PantallaFinal'),bP(5),bP(6),bS(7,'GAME OVER'),bS(8,'Reintentar?'),bS(9,'Créditos')],[['1.then','2.in'],['2.then','3.in'],['4.then','5.in'],['5.then','6.in'],['7.value','5.text'],['8.value','6.text'],['9.value','3.text']]), pts:30}
    ]}
  ]},

  { id:'6-4', title:'Del simulador al editor real de UE 5.8', time:'14 min', blocks:[
    {t:'p', h:'Ya piensas en nodos: es momento de conocer la casa real. <b>Unreal Engine 5.8</b> se descarga gratis desde el <b>Epic Games Launcher</b> (epicgames.com → Descargar). El motor pesa ~60 GB y quiere una computadora con buena GPU, pero para APRENDER Blueprints basta cualquier máquina media.'},
    {t:'list', items:[
      '<b>1.</b> Crea una cuenta gratuita de Epic Games e instala el <b>Epic Games Launcher</b>.',
      '<b>2.</b> Pestaña «Unreal Engine» → Unreal Engine 5.8 → Instalar (elige la versión 5.8.x más reciente).',
      '<b>3.</b> Nuevo proyecto desde una <b>plantilla</b>: «Blank» o «Third Person» (con personaje jugable listo).',
      '<b>4.</b> Doble clic en un Blueprint (por ejemplo el personaje) → pestaña <b>Event Graph</b>: ¡el mismo lienzo de este curso!',
      '<b>5.</b> Clic derecho para buscar nodos por nombre («Print String»), arrastra pines para conectar y el botón <b>Compile</b> valida; <b>Play</b> ejecuta.'
    ]},
    {t:'table', head:['En este curso','En el editor real','Traducción'], rows:[
      ['▶ Ejecutar','Botón Play (o PIE)','Corre la simulación'],
      ['Output Log','Output Log / pantalla','Ahí caen los Print String'],
      ['Palette de nodos','Clic derecho → búsqueda','Miles de nodos más'],
      ['⚠️ en español','Error rojo + Compile','La idea es la misma: lee el mensaje'],
      ['Variables del panel','My Blueprint → Variables','Con tipo y valor por defecto']
    ]},
    {t:'warn', title:'⚠️ Diferencias que notarás', h:'El UE real trae VECTORES (posición X,Y,Z), actores, componentes y físicas: conceptos nuevos SOBRE lo que ya sabes. Los nodos de este curso existen casi con el mismo nombre; lo que cambia es el mundo alrededor. Tu base de flujo, variables, ciclos y eventos traslada completa.'},
    {t:'quiz', questions:[
      {type:'mc', q:'¿Desde dónde se instala Unreal Engine?', options:['Steam','Epic Games Launcher','La Microsoft Store','Un USB de la escuela'], correct:1, pts:10, explain:'El Epic Games Launcher gestiona motor, versiones y proyectos.'},
      {type:'mc', q:'En el editor real, el grafo de un Blueprint vive en la pestaña…', options:['Viewport','Event Graph','Details','Content Browser'], correct:1, pts:10, explain:'Event Graph: el lienzo de nodos, gemelo del simulador del curso.'},
      {type:'tf', q:'En el editor real se buscan nodos con clic derecho escribiendo su nombre.', options:['Verdadero','Falso'], correct:0, pts:10, explain:'Clic derecho abre el buscador: escribe «print» y ahí está Print String.'}
    ]}
  ]}
]});

MODULES.push({
  id:'m7', emoji:'🏆', name:'Proyecto final y examen', color:'#eab308',
  desc:'«Defensa de la Librería Esperanza»: tu primer juego completo en Blueprints.',
  lessons:[
  { id:'7-1', title:'Proyecto I: la invasión de los slimes', time:'16 min', blocks:[
    {t:'p', h:'Momento de usar todo: los slimes han invadido la <b>Librería Esperanza</b> y tú programas su defensa. La partida tiene <b>vida 20</b> y <b>monedas 0</b>. Cada slime que ataca quita vida; cada slime derrotado paga monedas. En esta lección: el arranque, las oleadas y los ataques.'},
    {t:'info', title:'ℹ️ El plan de los 3 días', h:'Lección 7-1: estado inicial + oleadas + ataques (hoy). 7-2: botín, acumuladores y reporte. 7-3: menú de turnos con Custom Events y pantalla final. Al terminar tendrás un juego completo por turnos hecho 100% con nodos.'},
    {t:'quiz', questions:[
      {type:'mc', q:'¿Qué conviene hacer PRIMERO en el BeginPlay del juego?', options:['Imprimir la pantalla final','Inicializar las variables (vida, monedas) con Set','Llamar al evento de turnos','Nada'], correct:1, pts:10, explain:'Sin estado inicial, los primeros Get fallan: primero las cajas, después el juego.'},
      {type:'tf', q:'Las oleadas (cantidad fija de rondas) se recorren naturalmente con un ForLoop.', options:['Verdadero','Falso'], correct:0, pts:10, explain:'Sabes cuántas son: ForLoop 1..2 para dos oleadas.'}
    ]},
    {t:'bpex', title:'🧪 Proyecto · Fase 1: la defensa despierta', tasks:[
      {q:'FASE 1 · Estado inicial: <code>vida</code> = 20, <code>monedas</code> = 0. Imprime <code>Defensa iniciada</code>, <code>Vida: 20</code> y <code>Monedas: 0</code> (los dos últimos con Concat).', hint:'Set, Set, Print, Concat+Get, Concat+Get en cadena. Los literales: "Vida: " y "Monedas: ".', check:{lines:['Defensa iniciada','Vida: 20','Monedas: 0'], vars:{vida:20,monedas:0}}, solution:bG([bE(1),bSet(2,'vida'),bSet(3,'monedas'),bP(4),bGet(5,'vida'),bGet(6,'monedas'),bCat(7),bCat(8),bP(9),bP(10),bI(11,20),bS(12,'Vida: '),bS(13,'Monedas: '),bI(14,0),bS(15,'Defensa iniciada')],[['1.then','2.in'],['11.value','2.value'],['14.value','3.value'],['2.then','3.in'],['3.then','4.in'],['15.value','4.text'],['4.then','9.in'],['9.then','10.in'],['12.value','7.a'],['5.value','7.b'],['7.result','9.text'],['13.value','8.a'],['6.value','8.b'],['8.result','10.text']]), pts:35},
      {q:'FASE 1 · Las oleadas: ForLoop <code>1..2</code> que imprime <code>Oleada 1</code>, <code>Oleada 2</code>, y al terminar (Completed) imprime <code>¡Defiende la librería!</code>.', hint:'Cuerpo: Concat "Oleada " + Index. Completed → print.', check:{lines:['Oleada 1','Oleada 2','¡Defiende la librería!']}, solution:bG([bE(1),bFor(2),bCat(3),bP(4),bP(5),bTos(6),bS(7,'Oleada '),bS(8,'¡Defiende la librería!'),bI(9,1),bI(10,2)],[['1.then','2.in'],['9.value','2.first'],['10.value','2.last'],['2.body','4.in'],['7.value','3.a'],['2.index','6.value'],['6.result','3.b'],['3.result','4.text'],['2.completed','5.in'],['8.value','5.text']]), pts:30},
      {q:'FASE 1 · Los slimes: dentro del ForLoop 1..2, un ForEach sobre <code>["Burbuja","Viscoso"]</code> imprime <code>¡Slime Burbuja ataca!</code>, etc. (Concat "¡Slime " + Element + " ataca!"). Cuatro líneas en total.', hint:'Concat 1: "¡Slime " + Element. Concat 2: resultado + " ataca!".', check:{lines:['¡Slime Burbuja ataca!','¡Slime Viscoso ataca!','¡Slime Burbuja ataca!','¡Slime Viscoso ataca!']}, solution:bG([bE(1),bFor(2),bEach(3),bCat(4),bCat(5),bP(6),bArr(7,['Burbuja','Viscoso']),bS(8,'¡Slime '),bS(9,' ataca!'),bI(10,1),bI(11,2)],[['1.then','2.in'],['10.value','2.first'],['11.value','2.last'],['2.body','3.in'],['7.array','3.array'],['3.body','6.in'],['8.value','4.a'],['3.element','4.b'],['4.result','5.a'],['9.value','5.b'],['5.result','6.text']]), pts:40},
      {q:'FASE 1 · El daño: <code>vida</code> = 20; ForLoop 1..2 con ForEach de 2 slimes, donde CADA slime quita <code>3</code> de vida (sin prints en el cuerpo). Al final (Completed) imprime <code>Vida final: 8</code> (Concat). Vida queda en 8.', hint:'Cuerpo del ForEach: Set vida = Get vida − 3. Son 2×2 = 4 restas: 20 − 12 = 8.', check:{lines:['Vida final: 8'], vars:{vida:8}}, solution:bG([bE(1),bSet(2,'vida'),bFor(3),bEach(4),bSet(5,'vida'),bGet(6,'vida'),bAr(7,'-'),bI(8,20),bI(9,3),bP(10),bCat(11),bTos(12),bS(13,'Vida final: '),bArr(14,['Slime 1','Slime 2']),bI(15,1),bI(16,2)],[['1.then','2.in'],['8.value','2.value'],['2.then','3.in'],['15.value','3.first'],['16.value','3.last'],['3.body','4.in'],['14.array','4.array'],['4.body','5.in'],['6.value','7.a'],['9.value','7.b'],['7.result','5.value'],['3.completed','10.in'],['6.value','12.value'],['13.value','11.a'],['12.result','11.b'],['11.result','10.text']]), pts:45},
      {q:'FASE 1 · Las recompensas: <code>monedas</code> = 0; ForEach sobre <code>["Slime A","Slime B","Slime C"]</code> suma <code>+5</code> monedas por cada uno; en Completed imprime <code>Monedas: 15</code>.', hint:'Cuerpo: Set monedas = Get monedas + 5. Completed: Concat "Monedas: " + Get.', check:{lines:['Monedas: 15'], vars:{monedas:15}}, solution:bG([bE(1),bSet(2,'monedas'),bEach(3),bSet(4,'monedas'),bGet(5,'monedas'),bAr(6,'+'),bI(7,0),bI(8,5),bP(9),bCat(10),bArr(11,['Slime A','Slime B','Slime C']),bS(12,'Monedas: ')],[['1.then','2.in'],['7.value','2.value'],['2.then','3.in'],['11.array','3.array'],['3.body','4.in'],['5.value','6.a'],['8.value','6.b'],['6.result','4.value'],['3.completed','9.in'],['5.value','10.b'],['12.value','10.a'],['10.result','9.text']]), pts:40}
    ]}
  ]},

  { id:'7-2', title:'Proyecto II: botín, acumuladores y reporte', time:'16 min', blocks:[
    {t:'p', h:'La defensa funciona; ahora la economía. Cada slime derrotado suelta botín (<code>10, 15, 5</code> monedas), tu acumulador lo suma, y un Branch decide si te ganaste el <b>bonus</b>. Cierras con el reporte de ronda: el print profesional que resume la partida.'},
    {t:'quiz', questions:[
      {type:'mc', q:'El acumulador de botín (total = total + Element) debe estar…', options:['Antes del ForEach','En el cuerpo del ForEach','En el Completed','En otro BeginPlay'], correct:1, pts:10, explain:'Cada vuelta aporta: el Set acumulador vive dentro del cuerpo.'},
      {type:'tf', q:'El print del total va mejor en Completed que dentro del cuerpo (así se imprime UNA sola vez, al final).', options:['Verdadero','Falso'], correct:0, pts:10, explain:'Dentro del cuerpo imprimiría el total parcial en cada vuelta; en Completed, el definitivo.'}
    ]},
    {t:'bpex', title:'🧪 Proyecto · Fase 2: la economía', tasks:[
      {q:'Botín total: <code>total</code> = 0; ForEach sobre <code>[10,15,5]</code> suma cada Element; en Completed imprime el total: <code>30</code>.', hint:'El patrón acumulador completo del módulo 6.', check:{lines:['30'], vars:{total:30}}, solution:bG([bE(1),bSet(2,'total'),bEach(3),bSet(4,'total'),bGet(5,'total'),bP(6),bArr(7,[10,15,5]),bAr(8,'+'),bI(9,0)],[['1.then','2.in'],['9.value','2.value'],['2.then','3.in'],['7.array','3.array'],['3.body','4.in'],['5.value','8.a'],['3.element','8.b'],['8.result','4.value'],['3.completed','6.in'],['5.value','6.text']]), pts:30},
      {q:'Bonus: continúa la lógica — si <code>total >= 25</code> imprime <code>¡Bonus desbloqueado!</code>; si no, <code>Sin bonus</code>. Con [10,15,5] sale el bonus.', hint:'Completed → Branch con Comparar >= 20… digo, >= 25.', check:{lines:['¡Bonus desbloqueado!'], requireNodes:['branch']}, solution:bG([bE(1),bSet(2,'total'),bEach(3),bSet(4,'total'),bGet(5,'total'),bBr(6),bP(7),bP(8),bCmp(9,'>='),bI(10,25),bArr(11,[10,15,5]),bAr(12,'+'),bI(13,0),bS(14,'¡Bonus desbloqueado!'),bS(15,'Sin bonus')],[['1.then','2.in'],['13.value','2.value'],['2.then','3.in'],['11.array','3.array'],['3.body','4.in'],['5.value','12.a'],['3.element','12.b'],['12.result','4.value'],['3.completed','6.in'],['5.value','9.a'],['10.value','9.b'],['9.result','6.cond'],['6.true','7.in'],['6.false','8.in'],['14.value','7.text'],['15.value','8.text']]), pts:35},
      {q:'Reporte de ronda: imprime <code>Total: 30</code> (Concat "Total: " + Get total, con total = 30 ya acumulado con el ForEach de [10,15,5]).', hint:'Puedes acumular y luego imprimir con etiqueta: "Total: " + To String(Get total).', check:{lines:['Total: 30']}, solution:bG([bE(1),bSet(2,'total'),bEach(3),bSet(4,'total'),bGet(5,'total'),bAr(6,'+'),bI(7,0),bArr(8,[10,15,5]),bCat(9),bP(10),bTos(11),bS(12,'Total: ')],[['1.then','2.in'],['7.value','2.value'],['2.then','3.in'],['8.array','3.array'],['3.body','4.in'],['5.value','6.a'],['3.element','6.b'],['6.result','4.value'],['3.completed','10.in'],['5.value','11.value'],['12.value','9.a'],['11.result','9.b'],['9.result','10.text']]), pts:30},
      {q:'Guarda el botín: <code>inv</code> = []; agrega <code>"pocion"</code> y <code>"espada"</code> (patrón Add + Set); ForEach imprime <code>Guardado: pocion</code> y <code>Guardado: espada</code>.', hint:'Set inv → Set inv(Add(Get inv)) → Set inv(Add(Get inv)) → ForEach → Concat.', check:{lines:['Guardado: pocion','Guardado: espada'], vars:{inv:['pocion','espada']}}, solution:bG([bE(1),bSet(2,'inv','array'),bSet(3,'inv','array'),bSet(4,'inv','array'),bAdd(5),bAdd(6),bGet(7,'inv','array'),bGet(8,'inv','array'),bGet(9,'inv','array'),bEach(10),bCat(11),bP(12),bArr(13,[]),bS(14,'pocion'),bS(15,'espada'),bS(16,'Guardado: ')],[['1.then','2.in'],['13.array','2.value'],['2.then','3.in'],['7.value','5.array'],['14.value','5.item'],['5.result','3.value'],['3.then','4.in'],['8.value','6.array'],['15.value','6.item'],['6.result','4.value'],['4.then','10.in'],['9.value','10.array'],['10.body','12.in'],['16.value','11.a'],['10.element','11.b'],['11.result','12.text']]), pts:40},
      {q:'Estado final: <code>vida</code> = 0; Branch <code>vida <= 0</code>: True imprime <code>La librería cayó...</code>, False <code>¡La librería sigue en pie!</code>.', hint:'Con vida en 0, la condición da true: la rama triste.', check:{lines:['La librería cayó...']}, solution:bG([bE(1),bSet(2,'vida'),bBr(3),bP(4),bP(5),bGet(6,'vida'),bCmp(7,'<='),bI(8,0),bS(9,'La librería cayó...'),bS(10,'¡La librería sigue en pie!')],[['1.then','2.in'],['8.value','2.value'],['2.then','3.in'],['6.value','7.a'],['8.value','7.b'],['7.result','3.cond'],['3.true','4.in'],['3.false','5.in'],['9.value','4.text'],['10.value','5.text']]), pts:25}
    ]}
  ]},

  { id:'7-3', title:'Proyecto III: menú de turnos y pantalla final', time:'16 min', blocks:[
    {t:'p', h:'El cierre de oro: organizar el juego como lo haría un estudio. Un evento <code>TurnoJugador</code>, un <code>MostrarMenu</code>, una <code>PantallaFinal</code>… y un BeginPlay que solo coordina llamadas. Cuando termines estas 5 tareas, tendrás un juego por turnos completo, hecho pieza por pieza como los profesionales.'},
    {t:'quiz', questions:[
      {type:'mc', q:'¿Por qué el menú vive en un Custom Event y no suelto en el BeginPlay?', options:['Porque es obligatorio','Para reutilizarlo cada vez que el jugador regresa al menú','Porque los prints no funcionan en BeginPlay','Para que corra más rápido'], correct:1, pts:10, explain:'Cada vez que la partida vuelve al menú, basta un Call: lógica una vez, uso infinito.'},
      {type:'tf', q:'Un Custom Event puede leer las variables del juego (vida, monedas) sin recibirlas por cable.', options:['Verdadero','Falso'], correct:0, pts:10, explain:'Las variables son compartidas: un Get dentro del evento lee el valor actual del juego.'}
    ]},
    {t:'bpex', title:'🧪 Proyecto · Fase 3: el juego terminado', tasks:[
      {q:'Turno del jugador: evento <code>TurnoJugador</code> que imprime <code>>> Turno del jugador</code>; BeginPlay lo llama y luego imprime <code>Esperando acción...</code>. Debe tener event y call.', hint:'El evento imprime el encabezado del turno; el Call continúa con la espera.', check:{lines:['>> Turno del jugador','Esperando acción...'], requireNodes:['event_custom','call_custom']}, solution:bG([bE(1),bCall(2,'TurnoJugador'),bP(3),bCev(4,'TurnoJugador'),bP(5),bS(6,'>> Turno del jugador'),bS(7,'Esperando acción...')],[['1.then','2.in'],['2.then','3.in'],['4.then','5.in'],['6.value','5.text'],['7.value','3.text']]), pts:30},
      {q:'Menú reutilizable: evento <code>MostrarMenu</code> imprime <code>MENÚ</code>, <code>1. Defender</code>, <code>2. Curarse</code>; BeginPlay lo llama y después imprime <code>Elige: </code>.', hint:'Tres prints dentro del evento, el "Elige: " después del Call.', check:{lines:['MENÚ','1. Defender','2. Curarse','Elige: ']}, solution:bG([bE(1),bCall(2,'MostrarMenu'),bP(3),bCev(4,'MostrarMenu'),bP(5),bP(6),bP(7),bS(8,'MENÚ'),bS(9,'1. Defender'),bS(10,'2. Curarse'),bS(11,'Elige: ')],[['1.then','2.in'],['2.then','3.in'],['4.then','5.in'],['5.then','6.in'],['6.then','7.in'],['8.value','5.text'],['9.value','6.text'],['10.value','7.text'],['11.value','3.text']]), pts:30},
      {q:'Acción elegida: <code>opcion</code> = 1; Branch con <code>opcion == 1</code> cuya rama True llama al evento <code>Defender</code> (imprime <code>¡Muros de libros alzados!</code>). Debe incluir branch y call_custom.', hint:'Branch True → Call Defender; el evento vive aparte con su print.', check:{lines:['¡Muros de libros alzados!'], requireNodes:['branch','call_custom']}, solution:bG([bE(1),bSet(2,'opcion'),bBr(3),bCall(4,'Defender'),bGet(5,'opcion'),bCmp(6,'=='),bI(7,1),bCev(8,'Defender'),bP(9),bS(10,'¡Muros de libros alzados!')],[['1.then','2.in'],['7.value','2.value'],['2.then','3.in'],['5.value','6.a'],['7.value','6.b'],['6.result','3.cond'],['3.true','4.in'],['8.then','9.in'],['10.value','9.text']]), pts:40},
      {q:'Pantalla de leyenda: <code>monedas</code> = 30; Branch <code>monedas >= 20</code> → True llama al evento <code>PantallaFinal</code> que imprime <code>La librería es leyenda</code> y <code>Créditos: tú</code>.', hint:'La condición compara la variable; el evento es la pantalla completa.', check:{lines:['La librería es leyenda','Créditos: tú']}, solution:bG([bE(1),bSet(2,'monedas'),bBr(3),bCall(4,'PantallaFinal'),bGet(5,'monedas'),bCmp(6,'>='),bI(7,30),bI(8,20),bCev(9,'PantallaFinal'),bP(10),bP(11),bS(12,'La librería es leyenda'),bS(13,'Créditos: tú')],[['1.then','2.in'],['7.value','2.value'],['2.then','3.in'],['5.value','6.a'],['8.value','6.b'],['6.result','3.cond'],['3.true','4.in'],['9.then','10.in'],['10.then','11.in'],['12.value','10.text'],['13.value','11.text']]), pts:40},
      {q:'LA CORRIDA COMPLETA: <code>oro</code> = 0; ForLoop 1..3 suma <code>+10</code> al oro por vuelta; al terminar llama al evento <code>Reporte</code> que imprime <code>Oro final: 30</code> (Concat dentro del evento, leyendo la variable). Oro queda en 30. Debe tener call_custom.', hint:'El evento Reporte lee con Get el oro acumulado: las variables son compartidas.', check:{lines:['Oro final: 30'], vars:{oro:30}, requireNodes:['call_custom']}, solution:bG([bE(1),bSet(2,'oro'),bFor(3),bSet(4,'oro'),bGet(5,'oro'),bAr(6,'+'),bI(7,0),bI(8,10),bI(9,1),bI(10,3),bCall(11,'Reporte'),bCev(12,'Reporte'),bCat(13),bP(14),bTos(15),bS(16,'Oro final: ')],[['1.then','2.in'],['7.value','2.value'],['2.then','3.in'],['9.value','3.first'],['10.value','3.last'],['3.body','4.in'],['5.value','6.a'],['8.value','6.b'],['6.result','4.value'],['3.completed','11.in'],['12.then','14.in'],['5.value','15.value'],['16.value','13.a'],['15.result','13.b'],['13.result','14.text']]), pts:50}
    ]}
  ]},

  { id:'7-4', title:'Estrategia del examen + el horizonte UE6', time:'10 min', blocks:[
    {t:'p', h:'Llegaste al final del curso: piensas en nodos, variables, ciclos, eventos y estados. El <b>Examen Final</b> son 30 preguntas (300 puntos) de TODO el recorrido, con 210 (70%) para aprobar. Se califica al instante y tu boleta lo registra; puedes repetirlo cuando quieras.'},
    {t:'list', items:[
      'Repasa el mazo <b>SRS uecore</b>: las tarjetas cubren exactamente los conceptos del examen.',
      'Vuelve a ejecutar los ejercicios del proyecto (7-1 a 7-3): el examen adora preguntas de «¿qué imprime este grafo?».',
      'Cuidado con las trampas: ForLoop INCLUSIVO, índices desde 0, int/int que TRUNCA, y el orden de los Custom Events (lo más profundo termina primero).',
      'Lee las preguntas completas: «¿qué imprime?» pide la salida EXACTA, línea por línea.'
    ]},
    {t:'srs', deck:'uecore', sub:'Último repaso antes del examen: 2 minutos que valen oro.'},
    {t:'milestone', title:'🎓 Tu horizonte: UE 5.8 hoy, UE 6 mañana', h:'Terminaste con la misma caja de herramientas que usan los estudios: flujo, datos, colecciones, eventos y estados. El siguiente paso si el engine te atrapó: instalar UE 5.8 real (lección 6-4) y seguir con Blueprints Visual Scripting for UE5 (Romero & Sewell). Cuando UE 6 llegue (Early Access fines de 2027), Verse será el nuevo idioma — pero la lógica que aquí dominas es la misma de siempre: variables, decisiones, ciclos y eventos. Nos vemos en el examen. 🎮'},
    {t:'nav', lesson:'examen', label:'📝 Presentar el Examen Final'}
  ]}
]});

/* ============================================================
   EXAMEN FINAL · 30 preguntas × 10 pts = 300 (70% aprueba)
   ============================================================ */
const EXAM = {
  timeMin: 40,
  questions: [
    {type:'mc',   q:'M0 · Los Blueprints de Unreal son…', options:['Un lenguaje de texto compilado','Programación visual con nodos y cables','Un programa de modelado 3D','Un plugin de sonido'], correct:1, pts:10, explain:'Visual scripting: se construye lógica conectando nodos con cables.'},
    {type:'mc',   q:'M0 · Las flechas blancas entre nodos representan…', options:['El flujo de datos','El orden de ejecución','Errores de conexión','Animaciones'], correct:1, pts:10, explain:'Exec blanco = «ejecuta lo que sigue». Los cables de color llevan datos.'},
    {type:'tf',   q:'M0 · Para este curso NO hace falta instalar Unreal Engine: el simulador corre en el navegador.', options:['Verdadero','Falso'], correct:0, pts:10, explain:'El editor real se instala en la lección 6-4 si quieres dar el salto.'},
    {type:'mc',   q:'M1 · El pin Text de un Print String es de color…', options:['Rojo (bool)','Teal (int)','Verde (float)','Magenta (string)'], correct:3, pts:10, explain:'Text es string: magenta. Los números se convierten solos al entrar.'},
    {type:'mc',   q:'M1 · Una entrada de datos puede recibir…', options:['Varios cables','Dos cables máximo','Un solo cable','Ninguno: solo salen'], correct:2, pts:10, explain:'Una entrada, un cable. Una salida puede alimentar muchas entradas.'},
    {type:'mc',   q:'M1 · To Int (Truncate) aplicado a 7.8 da…', options:['8','7','7.8','-7'], correct:1, pts:10, explain:'Trunca hacia cero: corta el decimal, no redondea.'},
    {type:'fill', q:'M1 · Nombre del nodo que convierte 9.9 en 9 (escribe to_int o to int):', accept:['to_int','to int','toint'], re:'^\\s*to[_ ]?int.*$', pts:10, explain:'To Int (Truncate) corta hacia cero: 9.9 → 9.'},
    {type:'mc',   q:'M2 · ¿Qué nodo ESCRIBE un valor en una variable?', options:['Get','Set','Print','Make Array'], correct:1, pts:10, explain:'Set guarda (y expone el valor); Get solo lee.'},
    {type:'fill', q:'M2 · La salida de un nodo Comparar siempre es de tipo… (bool o boolean):', accept:['bool','boolean'], re:'^\\s*bool.*$', pts:10, explain:'Comparar fabrica el cable rojo de las decisiones.'},
    {type:'mc',   q:'M2 · Con dos ints, 10 / 4 en Unreal da…', options:['2.5','2','3','Error'], correct:1, pts:10, explain:'int/int trunca hacia cero (C++): 2. Con floats daría 2.5.'},
    {type:'mc',   q:'M2 · El residuo -7 % 3 en Unreal/C++ es…', options:['2','-1','1','0'], correct:1, pts:10, explain:'Signo del dividendo: -1. (Python daría 2: convención distinta.)'},
    {type:'mc',   q:'M2 · true XOR true evalúa…', options:['true','false','1','Error'], correct:1, pts:10, explain:'XOR es true solo si los bools difieren: dos true → false.'},
    {type:'mc',   q:'M3 · El pin Condition de un Branch acepta únicamente…', options:['int','string','bool','array'], correct:2, pts:10, explain:'Solo bool: usa Comparar para fabricarlo desde un número.'},
    {type:'fill', q:'M3 · Nombre del nodo de decisión con salidas True y False:', accept:['branch','branch node'], re:'^\\s*branch.*$', pts:10, explain:'Branch: la flecha se bifurca según el bool.'},
    {type:'mc',   q:'M3 · ForLoop de First=1 a Last=5 ejecuta el cuerpo…', options:['4 veces','5 veces','6 veces','0 veces'], correct:1, pts:10, explain:'El Last es INCLUSIVO: 1,2,3,4,5.'},
    {type:'mc',   q:'M3 · El pin Index de un ForLoop se puede leer…', options:['En todo el grafo','Solo dentro del cuerpo del loop','Solo en el Completed','En otro evento'], correct:1, pts:10, explain:'Es contextual: existe durante cada vuelta, dentro del cuerpo.'},
    {type:'tf',   q:'M3 · Un WhileLoop cuya condición nunca se vuelve falsa congela un juego real de UE.', options:['Verdadero','Falso'], correct:0, pts:10, explain:'El hilo del juego queda atrapado: algo del cuerpo debe cambiar la condición.'},
    {type:'fill', q:'M3 · Nodo que repite de First a Last (forloop o for loop):', accept:['forloop','for loop','for'], re:'^\\s*for\\s*loop.*$', pts:10, explain:'ForLoop: vueltas fijas, Index y Completed.'},
    {type:'mc',   q:'M3 · Un FlipFlop ejecutado 3 veces dispara…', options:['A, A, A','A, B, A','B, B, A','A y luego nada'], correct:1, pts:10, explain:'Alterna en cada ejecución: A, B, A.'},
    {type:'fill', q:'M4 · Nodo que cuenta los elementos de un array (array_len o array length):', accept:['array_len','array length','arraylen'], re:'^\\s*array[_ ]?len.*$', pts:10, explain:'Array Length cuenta elementos: un array de 7 devuelve 7 (índices 0..6).' },
    {type:'fill', q:'M4 · Nodo que recorre un array elemento por elemento (foreachloop o foreach):', accept:['foreachloop','foreach','for each'], re:'^\\s*for\\s*each.*$', pts:10, explain:'ForEachLoop: expone Element y Array Index en cada vuelta.'},
    {type:'mc',   q:'M4 · En la primera vuelta de un ForEachLoop, Array Index vale…', options:['1','0','-1','El largo'], correct:1, pts:10, explain:'Los índices de arrays empiezan en 0.'},
    {type:'mc',   q:'M4 · Array Add…', options:['Modifica el array original','Devuelve un array NUEVO con el elemento al final','Borra el último elemento','Devuelve un bool'], correct:1, pts:10, explain:'Por eso se combina con Set: para guardar el array crecido.'},
    {type:'fill', q:'M5 · Nodo que invoca (ejecuta) un Custom Event:', accept:['call','call custom event'], re:'^\\s*call.*$', pts:10, explain:'Call salta al evento, lo ejecuta completo y regresa.'},
    {type:'mc',   q:'M5 · BeginPlay llama a «Uno»; «Uno» llama a «Dos». ¿Qué termina de imprimirse primero?', options:['BeginPlay','Uno','Dos','Depende del azar'], correct:2, pts:10, explain:'La llamada más profunda termina primero; luego se regresa nivel por nivel.'},
    {type:'mc',   q:'M5 · Si un Call apunta a un evento que no existe…', options:['Se crea automáticamente','El motor avisa que no existe ese evento','Ejecuta un print vacío','Se reinicia el juego'], correct:1, pts:10, explain:'Revisa el nombre exacto del Custom Event.'},
    {type:'mc',   q:'M6 · La condición canónica de derrota (vida llega a cero o menos) es…', options:['vida > 0','vida <= 0','vida == 1','NOT vida'], correct:1, pts:10, explain:'<= 0 cubre cero y sobregolpes.'},
    {type:'mc',   q:'M6 · En el patrón acumulador (total = total + Element), el Set…', options:['Va antes del ciclo','Va DENTRO del cuerpo del ciclo','Va en el Completed','No existe'], correct:1, pts:10, explain:'Cada vuelta aporta su suma; el print del total sí va en Completed.'},
    {type:'tf',   q:'M6 · Los índices de un array en Blueprints empiezan en 1.', options:['Verdadero','Falso'], correct:1, pts:10, explain:'Falso: empiezan en 0. El último índice es Length − 1.'},
    {type:'mc',   q:'M7 · En el proyecto, las oleadas (rondas fijas) y los slimes (colección) se recorren con…', options:['ForLoop y ForEachLoop respectivamente','Dos WhileLoop','Dos Sequence','Branch anidados'], correct:0, pts:10, explain:'Cantidad conocida → ForLoop; colección → ForEach. El combo del juego.'}
  ]
};
